### PR TITLE
phoneNumber descriptions alignment to the other APIs

### PR DESCRIPTION
**Pull request by monamok**
#### What type of PR is this?

Add one of the following kinds:
* enhancement/feature

#### What this PR does / why we need it:
I checked the other APIs and '+' is optional but here it's required and it's better to align it so it's uniform. 

#### Which issue(s) this PR fixes:

Fixes (https://github.com/camaraproject/NumberVerification/issues/42)

#### Special notes for reviewers:

@DT-DawidWroblewski @bigludo7 could you please review it.

### CODE REVIEW

**Review by bigludo7 — APPROVED** [review]
Looks good 
Thanks

**Comment by monamok** [comment]
@bigludo7 @DT-DawidWroblewski I also replaced the uml link with the one in main branch from this repo instead of the temporary one from my GIT repo. Please review.

**Review by bigludo7 — APPROVED** [review]
Look good for me

**Review by DT-DawidWroblewski — APPROVED** [review]
looks good

**Pull request merged**
