### PR TITLE
Consolidate API information into yaml file

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* cleanup
* documentation

#### What this PR does / why we need it:
1. Include missing documentation from md files into yaml file
2. Remove deprecated files under API_documentation folder
3. Fix UML image path

#### Which issue(s) this PR fixes:

Fixes (https://github.com/camaraproject/NumberVerification/issues/55) UML link in YAML is faulty
Fixes (https://github.com/camaraproject/NumberVerification/issues/54) Add documentation into API definition before release

#### Special notes for reviewers:

N/A

#### Changelog input
N/A

#### Additional documentation 

N/A

### CODE REVIEW

**Review by DT-DawidWroblewski — APPROVED** [review]
consolidation is fine, so I approve this PR, although network authentication description remains an issue #46

**Comment by ECORMAC** [comment]
Just one thing before we approve (or perhaps I need to create a new PR?).

In the current Yaml (3.0.3) reference is made to a number of security mechanims without explaination.

In the "resources and operations overview" a reference is made to "3-legged token".
The sequence diagram refers to "standard OAuth2 Authorization Code grant".
In the "securitySchemes" a reference is made to OIDC "three_legged: type: openIdConnect openIdConnectUrl: https://example.com/.well-known/openid-configuration".

It is difficult for the consumer / user to understand what security mechanims are recommeded. Is is OIDC (and if so do we recommend the use of identity tokens?), will OAuth access token suffice?

A specific directive for this API would help (perhaps the flows can be updated?).

**Review by bigludo7 — APPROVED** [review]
LGTM/

**Comment by DT-DawidWroblewski** [comment]
> Just one thing before we approve (or perhaps I need to create a new PR?).
> 
> In the current Yaml (3.0.3) reference is made to a number of security mechanims without explaination.
> 
> In the "resources and operations overview" a reference is made to "3-legged token". The sequence diagram refers to "standard OAuth2 Authorization Code grant". In the "securitySchemes" a reference is made to OIDC "three_legged: type: openIdConnect openIdConnectUrl: https://example.com/.well-known/openid-configuration".
> 
> It is difficult for the consumer / user to understand what security mechanims are recommeded. Is is OIDC (and if so do we recommend the use of identity tokens?), will OAuth access token suffice?
> 
> A specific directive for this API would help (perhaps the flows can be updated?).

@fernandopradocabrillo can you please provide fixes according to @ECORMAC comment? thx! (have OpenId connect instead of three-legged)

**Comment by ECORMAC** [comment]
Hi Again,
I would be more inclined to state what we originally stated (or at least I think we originallly stated??) - we go with 3-legged (using access tokens). However this may now be touching upon discussion ongoing in the identity&Consent group (#55).

**Comment by fernandopradocabrillo** [comment]
> > Just one thing before we approve (or perhaps I need to create a new PR?).
> > In the current Yaml (3.0.3) reference is made to a number of security mechanims without explaination.
> > In the "resources and operations overview" a reference is made to "3-legged token". The sequence diagram refers to "standard OAuth2 Authorization Code grant". In the "securitySchemes" a reference is made to OIDC "three_legged: type: openIdConnect openIdConnectUrl: https://example.com/.well-known/openid-configuration".
> > It is difficult for the consumer / user to understand what security mechanims are recommeded. Is is OIDC (and if so do we recommend the use of identity tokens?), will OAuth access token suffice?
> > A specific directive for this API would help (perhaps the flows can be updated?).
> 
> @fernandopradocabrillo can you please provide fixes according to @ECORMAC comment? thx! (have OpenId connect instead of three-legged)

@DT-DawidWroblewski  Yes! I was gonna do the same as in Sim swap and create a different PR, but I didn't have time on friday. 
I will create a new one and cover these comments

**Pull request merged**
