### PR TITLE
added Tests

### PR DESCRIPTION
**Pull request by questsin**
#### What type of PR is this?

Add one of the following kinds:

* tests

#### What this PR does / why we need it:

5GFF and Rogers Communications contributions from the test bed.
Example Testing Framework for Compliance and Conformance similar to other API

#### Special notes for reviewers:

Similar PRs were done for Location, OTP, and QoS repos.
Roadmap to cover all the Camara APIs within a few months.

### CODE REVIEW

**Review by bigludo7 — COMMENTED** [review]
Thanks for the contribution.
I'm concerned because my understanding was to use Gherkin .feature for test.
Need probably a discussion within Commonalities.

**Comment by questsin** [comment]
Developer Community is polygot. Even OpenAPI has code gens to support multiple languages in terms of Servers, Client SDKs. This can be easily translated to any language and framework of the day. Its just a start, but based on our real-life implementations and inspired by TMForum conformance and compliance tests in the same framework. My two cents.

**Comment by questsin** [comment]
It's also self contained and includes all the bells and whistles, batteries included and can run anywhere 😀

**Comment by shilpa-padgaonkar** [comment]
@questsin : Kindly refer to the commonalities agreed guideline for making test case contributions to a subproject. You can find the details under point (5) of [API-Readiness-Checklist.md ](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-Readiness-Checklist.md)

**Pull request closed without merging**
