### PR TITLE
Update error examples and add reference for x-correlator

### LINKED ISSUE #127: Update error examples and add reference for x-correlator
**Problem description**

@bigludo7 proposed changes to the number-verification.yaml with (to be closed) PR #123:
* to update error examples in YAML (see commit https://github.com/camaraproject/NumberVerification/commit/83fd1a22e4bba08c068b3fa2b654ba0d4138d37e)
* to add a reference for x-correclator (see commit https://github.com/camaraproject/NumberVerification/commit/65b1db0d15582f041a2eea68006bbe46ec71fd3f, with small fix https://github.com/camaraproject/NumberVerification/pull/123/commits/73ee72f9468ef66a5343c65d1c8179c4b3e804b2)

**Expected behavior**

Proposed changes should be applied to main in a separate PR before the (new) PR #126 get merged and the release candidate get created.

**Alternative solution**

**Additional context**

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* bug
* correction

#### What this PR does / why we need it:

- update error examples in YAML (see commit https://github.com/camaraproject/NumberVerification/commit/83fd1a22e4bba08c068b3fa2b654ba0d4138d37e)
- add a reference for x-correclator (see commit https://github.com/camaraproject/NumberVerification/commit/65b1db0d15582f041a2eea68006bbe46ec71fd3f, with small fix https://github.com/camaraproject/NumberVerification/commit/73ee72f9468ef66a5343c65d1c8179c4b3e804b2)

#### Which issue(s) this PR fixes:

Fixes #127

### CODE REVIEW

**Review by hdamker — APPROVED** [review]
LGTM

**Comment by fernandopradocabrillo** [comment]
@AxelNennker can you please approve this PR? I need the approval of another codeowner.
It is just to fix a PR that Ludovic created but since he is on holiday we couldn't update it so we have create it again.
Thanks!

**Comment by fernandopradocabrillo** [comment]
Hi @hdamker, I think that we can merge this PR if you are okey with it. It's okey for me if  you prefer to wait for @AxelNennker review.

**Comment by hdamker** [comment]
@fernandopradocabrillo Yes, same changes as @bigludo7 had done and they LGTM. Will merge on behalf.

**Pull request merged**
