### PR TITLE
Optional parameters proposed by TIM

### PR DESCRIPTION
**Pull request by paulocesardiaslima**
Optional parameters proposed by TIM’s Number Verification API scenario as described in GSMA document “IDY.54 Mobile Connect Verified MSISDN Definition and Technical Requirements”, as cited below:

“As an option, for the Mobile Connect Verified MSISDN service, the ID GW Authorization Server may also check the source IP address to identify that it is from the core network".

### CODE REVIEW

**Comment by DT-DawidWroblewski** [comment]
Dear @paulocesardiaslima !
thanks for the proposal, although we're aiming to avoid passing additional content inside /token & /{resourceEndpoint} requests.

Therefore, I suggest you add optional headers, you'd like to introduce to **/authorize** endpoint request that is a part of MC Spec that is a part of this [PR](https://github.com/camaraproject/NumberVerification/pull/2).

Here's link to commit that contains recent version of yaml file:

[MC yaml](https://github.com/camaraproject/NumberVerification/pull/2/files#diff-7ad53c0c79deb168d7865a57ac89cabdb300577922209d79d7222cefd2a28ad6)

**Comment by paulocesardiaslima** [comment]
Dear Dawid, thanks for your comments.

Since our initial discussions about  NumberVerify API, TIM Brasil are not considering to implements Mobile Connect (MC) in TIM API implementation.  

The reference that I cited about MC was only regarding the part of "ID GW Authorization Server may also check the source IP address to identify that it is from the core network" that is part of TIM' SMV NumberVerify  solution with OAuth2.0 and JWT for security.

Since TIM expect to verify MSISDN informed by mobile user with DeviceIP from Service Provider BackEnd, we are considering user /verify (/openid/userinfo in previous YAML version) to send theses parameters and receive the validation result (true / false) from API.

Regarding this scenario, can we consider /verify (/openid/userinfo in previous YAML version) to these optional header parameters?

Thanks again.

BR,

Paulo.

**Comment by bigludo7** [comment]
Hello @paulocesardiaslima , @DT-DawidWroblewski 

To make sure Paulo to understand your requirement, you want to be able to challenge a msisdn providing IP & Port ?

In this case, perhaps, we can consider to pass these parameters in the POST request body with a structure similar to the one used in other CAMARA api like for example Check Device connectivity:
`  "ueId": {
    "externalId": "string",
    "msisdn": "123456789",
    "ipv4Addr": "string",
    "ipv6Addr": "string"
  },
  "uePort": string,`

I'm looking for consistency between all the API and used same 'pattern' when possible.

Could you please elaborate the requirement for the other parameters: X-Request-consentGranted, X-Request-callbackUrl and X-Request-returnUrl ? Thanks !

Adding @jlurien and @monamok in the loop to get their feedback.

**Comment by paulocesardiaslima** [comment]
Dear @bigludo7 , @DT-DawidWroblewski , @jlurien ,  @monamok.

Yes. TIM API want to be able to challenge a msisdn by verify providing IP & Port inside MNO network.

Please, check below our initial proposal API description for number Verify API, including the requirement for the other parameters.

thanks! 

BR,

Paulo Cesar.

API: 
  description: |
    ## Overview
    Validates that the MSISDN of the mobile device connected via the cellular network is using the IP address of the connection to the server of the service that is querying the API.
    
    ## 1. Introduction
    
    The CAMARA numberVerify API provides a service to MNO single sign-on for mobile applications (confirmation of subscriber number and IP used for application authentication without the need to use SMS or passwords).
    
    ## 2. Quick Start
 
    - The Mobile User inform MSISDN to verification.
    
    - BackEnd APP or Web Partner Application Server pass the IP address to TIM API GTW to validate MSISDN. 
    
    - TIM API GTW expose a standard Openverse API CAMARA numberVerify for NumberVerification.
    
    Before starting to use the API, the developer needs to know about the below specified details:
        
    **consentGranted**
    
    Indicates whether operator have consent from mobile phone number's owner to perform this request.
     
    **device_msisdn**
    
    Mobile phone number (MSISDN) to verify. The number must be in international format.
     
    **deviceIp**
    
    IPv4 or IPv6 address of the mobile device that will be verified with operator. 
     
    **devicePort**
    
    Port of the mobile device that will be verified with operator. Can be used only when "deviceIp" is also provided.
     
    **callbackUrl**
    
    Your URL that will be called to provide verification result when the process is complete. 
     
    **returnUrl**
    
    An URL to which the mobile device will be redirected to when verification is complete.
     
    As assumption we considering to verify the phone number of the device connected to our the mobile data network 4G and 5G.

    ## 3. Authentication and Authorization
    
    The numberVerify API makes use of the client credentials grant which is applicable for server to server use cases involving trusted partners or clients.
    In this method the API invoker client is registered as a confidential client with an authorization grant type of client\_credentials.
    
    Configure security access keys such as OAuth 2.0 client credentials to be used by Client applications which will invoke the numberVerify API.
    
    ## 4. API Documentation
    ## 4.1 Details    
    
    ### 4.1.1 User Stories
    - A service provider server serving a client application (Android or IOS app, or Web app), connected through cellular network, needs to validate the MSISDN of a user. 
    
    - To do this, it asks the user to enter their MSISDN, and then server(SP) executes the NumberVerification API, informing the MSISDN and the IP address of the cellular access of the client in question, used to inform the MSISDN to the server.
    
    - If the informed IP address is in use by the
    informed MSISDN, the API will return “OK” for the match. Otherwise, it will report “NOK”
    
    ### 4.1.2 API E2E Flows:
    - Mobile phone user with a mobile device connected via the cellular network accesses a service available on the public internet. 
    
    - This service provider asks for the MSISDN of the device and retrieves the access IP of that device.
    
    - NumberVerification call MNO server, informing MSISDN and public IP of the access.
    
    - API checks if there is a match between MSISDN and public IP on the operator
    
    - API responds to the server the result of the match check = OK/NOK (true/false)

**Comment by monamok** [comment]
Hello @paulocesardiaslima. 
In order to clarify the case, at the end we decided to have two different solutions in CAMARA for this API as between companies the roadmaps were not aligned. We included both YAML versions and their documentation in the main branch:

- https://github.com/camaraproject/NumberVerification/blob/main/code/API_definitions/numberVerify.yaml --> Based on MC
https://github.com/camaraproject/NumberVerification/blob/main/documentation/API_documentation/API_definition.md

- https://github.com/camaraproject/NumberVerification/blob/main/code/API_definitions/number_verification.yaml
https://github.com/camaraproject/NumberVerification/blob/main/documentation/API_documentation/NUMBER_VERIFICATION_API.md

In the first solution, the whole flow is included and it starts from authorize, continues with getting the token and then uses /openid/userinfo endpoint.
The second solution assumes that the user already got its three-legged token in the previous steps before calling this API (authenticating by the Network) and in the API the focus is just on verifying the number which receives and compares with the one that is associated with the token. The client must authenticate via IP to use this service and there is an specific error "NUMBER_VERIFICATION.USER_NOT_AUTHENTICATED_BY_IP" in case another method was used. This solution keeps the same format as other CAMARA APIs by including dedicated resources and keeping the authentication part outside of the API.

Please review both cases but from your comments it looks like you might want to open a new PR and include your suggestion in the MC solution where /authorize resource exists because in the second one the information must have been included in the token which is received.

**Comment by paulocesardiaslima** [comment]
Dear @monamok initially I analyzed Number Verify API as based on Mobile Connect Verified MSISDN standardized product. But in TIM Brasil we not have MC implemented. And we evaluated and proposed implements only the PATH /openid/userinfo - User Info from Dawid initial API proposal https://github.com/DT-DawidWroblewski/NumberVerification.

But after these your comments and explanations I realized that TIM Brasil API scenario is more related to second solution that you described:

"The second solution assumes that the user already got its three-legged token in the previous steps before calling this API (authenticating by the Network) and in the API the focus is just on verifying the number which receives and compares with the one that is associated with the token."

For this reason, I would like to proposed includes new header parameters in path /verify regarding https://github.com/camaraproject/NumberVerification/blob/main/code/API_definitions/number_verification.yaml API according TIM BRASIL's implementation scenario.

Our implementation is according this description: |
    ## Overview
    Validates that the MSISDN of the mobile device connected via the cellular network is using the IP address of the connection to the server of the service that is querying the API.
    
    ## 1. Introduction
    
    The CAMARA numberVerify API provides a service to MNO single sign-on for mobile applications (confirmation of subscriber number and IP used for application authentication without the need to use SMS or passwords).
    
    ## 2. Quick Start
 
    - The Mobile User inform MSISDN to verification.
    
    - BackEnd APP or Web Partner Application Server pass the IP address to TIM API GTW to validate MSISDN. 
    
    - TIM API GTW expose a standard Openverse API CAMARA numberVerify for NumberVerification.
    
    Before starting to use the API, the developer needs to know about the below specified details:
        
    **consentGranted**
    
    Indicates whether operator have consent from mobile phone number's owner to perform this request.
     
    **device_msisdn**
    
    Mobile phone number (MSISDN) to verify. The number must be in international format.
     
    **deviceIp**
    
    IPv4 or IPv6 address of the mobile device that will be verified with operator. 
     
    **devicePort**
    
    Port of the mobile device that will be verified with operator. Can be used only when "deviceIp" is also provided.
     
    **callbackUrl**
    
    Your URL that will be called to provide verification result when the process is complete. 
     
    **returnUrl**
    
    An URL to which the mobile device will be redirected to when verification is complete.
     
    As assumption we considering to verify the phone number of the device connected to our the mobile data network 4G and 5G.

    ## 3. Authentication and Authorization
    
    The numberVerify API makes use of the client credentials grant which is applicable for server to server use cases involving trusted partners or clients.
    In this method the API invoker client is registered as a confidential client with an authorization grant type of client\_credentials.
    
    Configure security access keys such as OAuth 2.0 client credentials to be used by Client applications which will invoke the numberVerify API.
    
    ## 4. API Documentation
    ## 4.1 Details    
    
    ### 4.1.1 User Stories
    - A service provider server serving a client application (Android or IOS app, or Web app), connected through cellular network, needs to validate the MSISDN of a user. 
    
    - To do this, it asks the user to enter their MSISDN, and then server(SP) executes the NumberVerification API, informing the MSISDN and the IP address of the cellular access of the client in question, used to inform the MSISDN to the server.
    
    - If the informed IP address is in use by the
    informed MSISDN, the API will return “OK” for the match. Otherwise, it will report “NOK”
    
    ### 4.1.2 API E2E Flows:
    - Mobile phone user with a mobile device connected via the cellular network accesses a service available on the public internet. 
    
    - This service provider asks for the MSISDN of the device and retrieves the access IP of that device.
    
    - NumberVerification call MNO server, informing MSISDN and public IP of the access.
    
    - API checks if there is a match between MSISDN and public IP on the operator
    
    - API responds to the server the result of the match check = OK/NOK (true/false)

**Comment by jpengar** [comment]
@paulocesardiaslima I'm speaking on behalf @monamok since she will be some days OOO until mid next week.

Regarding you proposal, it is pretty much aligned with the API goal since, at the end of the day, what you are suggesting is to verify an input phone number via the mobile network. BUT instead of doing it based on the phone number information associated to the access token, you suggest to provide the public IP as parameter. And validate whether the input phone number corresponds to the public IP also provided.

However from TEF we have some comments regarding your proposal:

* Proposal consist on including new custom headers in the HTTP request. From our point of view, headers should not be intended to be used for API specific functionality but for more traversal topics. Like including a request correlator (e.g. `x-correlator` header). We better suggest to include the required information in the request body.
* Also, it is being proposed to change `/verify` endpoint including this new feature (or API usage) mixing it with the existing definition based on access token information. We would suggest to actually define an additional dedicated endpoint/operation for the feature being proposed (`/verify-xxx`).
* `X-Request-consentGranted` header -> We don't see this header required. API client should have an access token with required scopes to consume the API and that token should be issued to the API Client IF and only IF there is user consent. API GW should only introspect access token to validate if required scope (e.g. number-verification-verify-read) is in place or not. This header is not considered in other operations or APIs.
* `X-Request-deviceIp` header -> Public IP would be defined as a request body parameter in the new endpoint/operation to validate by IP.
* `X-Request-devicePort` header -> If device port is also needed, it would be also defined as a request body parameter.
* `X-Request-callbackUrl` header -> Why are you proposing to have a callback URL. Are you suggesting to have an asynchronous design for this operation? If that is the case, that`s a strong reason to define it as an additional endpoint/operation. In your experience, how long would it take to validate the phone number against the Public IP in the network? Because if it is not possible to provide a synchronous response withing a given SLA, it may be also needed to define a notification event to let the API client know the final operation result or use pooling. In any case, if required it should be defined as a request body parameter instead.
* `X-Request-returnUrl` header -> Do you really need it? If so, what is it intended for? API logic is just intended to perform the number validation...

**Comment by bigludo7** [comment]
Hello
I'm aligned with @jpengar comments about header vs body attributes 'localisation'.

This was also my comment some week ago, for global Camara API consistency, for device ip, device port and callback url we should use strictly same grammar than in other Camara api (in the body, use of attributes ueId & uePorts).

**Comment by jpengar** [comment]
> Also I would like to align the understanding about @monamok YAML indication:
>
>https://github.com/camaraproject/NumberVerification/blob/main/code/API_definitions/number_verification.yaml
>
>About API Resources, Operations paths indicated:
>
>/verify
>/token
>/device-phone-number
>
>In which cases and scenarios you consider associated to the authenticated user's access token.

@paulocesardiaslima In [API definition](https://github.com/camaraproject/NumberVerification/blob/main/code/API_definitions/number_verification.yaml) there are only two paths:

1) /verify
2) /device-phone-number

image

And both endpoints/operation will be executed for the user that has authenticated via mobile network and so their `sub` (user identifier) is in the access token being use to invoke the API. It is also documented in API definition. E.g.

image

/token is not an endpoint included in the API definition. We are not following Mobile connect approach. For us, that endpoint is instead normally exposed by the Operator Auth server for API clients to get an access token as part of the authentication process. And later on, that access token is the one be used to invoke the API itself if the required scopes has been granted.

**Comment by pcdl1970** [comment]
Dear @jpengar,  @bigludo7, @monamok , @DT-DawidWroblewski  thanks again for all comments, answers and discussions about this API.

Please could you see the new PR regarding define an additional dedicated endpoint/operation for the feature being proposed by TIM (/verify-smv):

https://github.com/pcdl1970/NumberVerification/pull/3 

Best Regards.

Paulo Lima.

**Review by monamok — COMMENTED** [review]
In the meantime, I have some general questions @pcdl1970.

- In the new version, the authentication is with a three-legged access token but there were some previous comments about using ClientCredentials which is not included in the current version. Which method are you planning to use?
- About the resource and the tag (Silent Mobile Verification) I would change it because the whole API is about is a "Silent Mobile Verification" and it's better to differentiate it somehow and using something like /verify-ip for example.
- About the request body, what is the purpose of including consentGranted and callbackUrl? You already got a token, and in order to do that you already had the consent. And if you're returning true/false response why you need a callbackUrl?
- You added ueId object in oneOf structure which is applied to the current endpoints and it must not be added to those one. You might need to separate it and personalize the request body of the new endpoint. 
- About the input format consistency with other CAMARA IPs I agree with @bigludo7  but they’re currently being changed to be aligned with Commonalities (snake_case, user-friendy, …) so we can leave it for now and refactor them in a further version.

**Comment by pcdl1970** [comment]
Dear @monamok thanks again for your comments.

Please see my answers regarding your previous comments and questions:

•	In the new version, the authentication is with a three-legged access token but there were some previous comments about using ClientCredentials which is not included in the current version. Which method are you planning to use?

[paulolima] We are planning to use oAuth2 to Server (Service Provider) to Server (MNO) authentication.
I updated the YAML with this information.

•	About the resource and the tag (Silent Mobile Verification) I would change it because the whole API is about is a "Silent Mobile Verification" and it's better to differentiate it somehow and using something like /verify-ip for example.

[paulolima] Ok. Thanks for your suggestion. I updated the YAML with this resource and the tag /verify-ip.

•	About the request body, what is the purpose of including consentGranted and callbackUrl? You already got a token, and in order to do that you already had the consent. And if you're returning true/false response why you need a callbackUrl?

[paulolima] We 're returning true/false response. 
We considered previously consentGranted and callbackUrl to other scenario where we could return ASYNC response based in  callbackUrl information. But it will not be the case for this API proposal.
I updated the YAML  and removed them.

•	You added ueId object in oneOf structure which is applied to the current endpoints and it must not be added to those one. You might need to separate it and personalize the request body of the new endpoint.

[paulolima] Ok. I separated it and personalizes the request body of a new endpoint. I updated the YAML.

•	About the input format consistency with other CAMARA IPs I agree with @bigludo7 but they’re currently being changed to be aligned with Commonalities (snake_case, user-friendy, …) so we can leave it for now and refactor them in a further version.

[paulolima] Ok. I tried to follows with @bigludo7 indications to format consistency with other CAMARA APIs.

**Comment by monamok** [comment]
> 

Thank you @pcdl1970 fot the clarification. I put some comments on "https://github.com/camaraproject/NumberVerification/pull/20". I would like to keep asking you to bring the changes to this PR instead of openning a new PR. In case you want to continue woth the other one we can close this one. It's gonna be confusing to have two open PRs for the same usecase.

P.D. Sorry to ask but I'm not still sure if both @paulocesardiaslima and @pcdl1970 accounts are from one person or are you working together?

**Comment by pcdl1970** [comment]
Dear @monamok thanks for your answers. 

I reviewed your comments and updated the TIM proposal API YAML regarding https://github.com/camaraproject/NumberVerification/pull/20

If you agree I guess that I prefer to continue with the other PR, and we can close this one.

Since the first PR we made several modifications and new alignments about new operation/path and others.

Can we proceed in this way?

By the way, both @paulocesardiaslima and @pcdl1970 are my accounts (business and personal). I had some issues and limitations to access Github account using my business account  so I had to write some comments and submit PR using my personal email account also.

Best regards,

Paulo Cesar Dias Lima.

**Comment by DT-DawidWroblewski** [comment]
Closing this one. Work continues elsewhere (PR#20)[https://github.com/camaraproject/NumberVerification/pull/20].

**Pull request closed without merging**
